<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE mast[
<!ELEMENT mast (model, alphabet, motifs, sequences, runtime)>
<!ATTLIST mast version CDATA #REQUIRED release CDATA #REQUIRED>
<!ELEMENT model (command_line, max_correlation, remove_correlated, strand_handling, translate_dna, max_seq_evalue,
    adj_hit_pvalue, max_hit_pvalue, max_weak_pvalue, host, when)>
<!ELEMENT command_line (#PCDATA)>
<!ELEMENT max_correlation (#PCDATA)>
<!ELEMENT remove_correlated EMPTY>
<!ATTLIST remove_correlated value (y|n) #REQUIRED>
<!ELEMENT strand_handling EMPTY>
<!ATTLIST strand_handling value (combine|separate|norc|protein) #REQUIRED>
<!ELEMENT translate_dna EMPTY>
<!ATTLIST translate_dna value (y|n) #REQUIRED>
<!ELEMENT max_seq_evalue (#PCDATA)>
<!ELEMENT adj_hit_pvalue EMPTY>
<!ATTLIST adj_hit_pvalue value (y|n) #REQUIRED>
<!ELEMENT max_hit_pvalue (#PCDATA)>
<!ELEMENT max_weak_pvalue (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT when (#PCDATA)>
<!ELEMENT alphabet (letter+)>
<!ATTLIST alphabet type (amino-acid|nucleotide) #REQUIRED bg_source (preset|file|sequence_composition) #REQUIRED bg_file CDATA #IMPLIED>
<!ELEMENT letter EMPTY>
<!ATTLIST letter symbol CDATA #REQUIRED ambig (y|n) "n" bg_value CDATA #IMPLIED>
<!ELEMENT motifs (motif+,correlation*,nos*)>
<!ATTLIST motifs source CDATA #REQUIRED name CDATA #REQUIRED last_mod_date CDATA #REQUIRED>
<!ELEMENT motif EMPTY>
<!-- num is simply the loading order of the motif, it's superfluous but makes things easier for XSLT -->
<!ATTLIST motif id ID #REQUIRED num CDATA #REQUIRED name CDATA #REQUIRED width CDATA #REQUIRED
   best_f CDATA #REQUIRED best_r CDATA #IMPLIED bad (y|n) "n">
<!-- for n > 1 motifs there should be (n * (n - 1)) / 2 correlations, obviously there are none for only 1 motif -->
<!ELEMENT correlation EMPTY>
<!ATTLIST correlation motif_a IDREF #REQUIRED motif_b IDREF #REQUIRED value CDATA #REQUIRED>
<!-- nos: Nominal Order and Spacing diagram, a rarely used feature where mast can adjust pvalues for an expected motif spacing -->
<!ELEMENT nos (expect+)>
<!-- length is in the same unit as the motifs, which is not always the same unit as the sequence -->
<!ATTLIST nos length CDATA #REQUIRED>
<!-- the expect tags are expected to be ordered by pos ascending -->
<!ELEMENT expect EMPTY>
<!ATTLIST expect pos CDATA #REQUIRED gap CDATA #REQUIRED motif IDREF #REQUIRED>
<!ELEMENT sequences (database+, sequence*)>
<!-- the database tags are expected to be ordered in file specification order -->
<!ELEMENT database EMPTY>
<!ATTLIST database id ID #REQUIRED num CDATA #REQUIRED source CDATA #REQUIRED name CDATA #REQUIRED last_mod_date CDATA #REQUIRED 
    seq_count CDATA #REQUIRED residue_count CDATA #REQUIRED type (amino-acid|nucleotide) #REQUIRED link CDATA #IMPLIED>
<!-- the sequence tags are expected to be ordered by best combined p-value (of contained score tags) ascending -->
<!ELEMENT sequence (score+,seg*)>
<!ATTLIST sequence id ID #REQUIRED db IDREF #REQUIRED num CDATA #REQUIRED name CDATA #REQUIRED comment CDATA "" length CDATA #REQUIRED>
<!ELEMENT score EMPTY>
<!-- frame is the starting offset for translation of dna sequences which gives the lowest pvalues for the provided protein motifs -->
<!ATTLIST score strand (both|forward|reverse) #REQUIRED frame (a|b|c) #IMPLIED combined_pvalue CDATA #REQUIRED evalue CDATA #REQUIRED>
<!-- within each sequence the seg tags are expected to be ordered by start ascending -->
<!ELEMENT seg (data,hit+)>
<!ATTLIST seg start CDATA #REQUIRED>
<!ELEMENT data (#PCDATA)>
<!-- within each seg the hit tags are expected to be ordered by pos ascending and then forward strand first -->
<!ELEMENT hit EMPTY>
<!-- gap, while superfluous, makes creating motif diagrams for the text version much easier when using XSLT -->
<!ATTLIST hit pos CDATA #REQUIRED gap CDATA #REQUIRED motif IDREF #REQUIRED pvalue CDATA #REQUIRED strand (forward|reverse) "forward" 
    match CDATA #REQUIRED translation CDATA #IMPLIED>
<!ELEMENT runtime EMPTY>
<!ATTLIST runtime cycles CDATA #REQUIRED seconds CDATA #REQUIRED>
]>
<mast version="4.8.1" release="Tue Feb  7 14:03:40 EST 2012">
	<model>
		<command_line>mast /tmp/meme.out.jbm1HF /tmp/memeseqsqgSRp5 -bfile /tmp/memebgBGpkgd -nostatus -ev 1500 -mev 99999 -mt 0.99 -nohtml -seqp -remcorr -oc /tmp/mastoutOQEmjw</command_line>
		<max_correlation>0.60</max_correlation>
		<remove_correlated value="y"/>
		<strand_handling value="combine"/>
		<translate_dna value="n"/>
		<max_seq_evalue>1.5e+03</max_seq_evalue>
		<adj_hit_pvalue value="y"/>
		<max_hit_pvalue>0.99</max_hit_pvalue>
		<max_weak_pvalue>0.99</max_weak_pvalue>
		<host>eric</host>
		<when>Wed Jul 31 10:50:04 2013</when>
	</model>
	<alphabet type="nucleotide" bg_source="file" bg_file="/tmp/memebgBGpkgd">
		<letter symbol="A" bg_value="0.187"/>
		<letter symbol="C" bg_value="0.313"/>
		<letter symbol="G" bg_value="0.313"/>
		<letter symbol="T" bg_value="0.187"/>
	</alphabet>
	<motifs source="/tmp/meme.out.jbm1HF" name="/tmp/meme.out.jbm1HF" last_mod_date="Wed Jul 31 10:50:04 2013">
		<motif id="motif_1" num="1" name="1" width="17" best_f="CTATCATAATTGTTCTG" best_r="CAGAACAATTATGATAG"/>
	</motifs>
	<sequences>
		<database id="db_1" num="1" source="/tmp/memeseqsqgSRp5" name="/tmp/memeseqsqgSRp5" last_mod_date="Wed Jul 31 10:50:04 2013" seq_count="403" residue_count="112840" type="nucleotide"/>
		<sequence id="seq_1_112" db="db_1" num="112" name="NP_281042.1" comment="" length="280">
			<score strand="both" combined_pvalue="5.62e-07" evalue="0.00023"/>
			<seg start="1">
				<data>
GTTGCCATCCTCGGTGAATACGGTTCGCTCCGGCGAAGATTGGAGGGCGGTGAGGCGGTCTTCGGTGTCGTCGTC
AGCGTCCCGCGTAACTGGCATATCAGGCCCTATGCAGCGGTGCTATCATATGTGTTTTGGTCGGCCTAAAACAGG
GCGTTTGTGGCGGTCATCGCGCTGAGCCGGAGGTTTATACCGCAAGCCGTTCGTATTCCGGGACACCGTGGCCGC
				</data>
				<hit pos="5" gap="4" motif="motif_1" pvalue="3.4e-01" strand="forward" match="+ +++ +  +++  +  "/>
				<hit pos="38" gap="16" motif="motif_1" pvalue="9.8e-01" strand="forward" match="  ++     + + +  +"/>
				<hit pos="68" gap="13" motif="motif_1" pvalue="8.8e-01" strand="forward" match="   ++ + ++ ++ + +"/>
				<hit pos="118" gap="33" motif="motif_1" pvalue="2.8e-07" strand="forward" match="++++++++ ++++++++"/>
				<hit pos="141" gap="6" motif="motif_1" pvalue="3.7e-01" strand="reverse" match="+ +++  +    + + +"/>
			</seg>
		</sequence>
		<sequence id="seq_1_347" db="db_1" num="347" name="NP_281043.1" comment="" length="280">
			<score strand="both" combined_pvalue="5.62e-07" evalue="0.00023"/>
			<seg start="1">
				<data>
CGAACAACACGTTGGTGCCGCCGTCGAGTGCGTCCCGGATCGCGTCCATCGCGGCCCGCTGGTTGTCGTACGGCG
				</data>
				<hit pos="21" gap="20" motif="motif_1" pvalue="4.8e-01" strand="forward" match="+  ++    + ++ + +"/>
			</seg>
			<seg start="151">
				<data>
GCTTGCGGTATAAACCTCCGGCTCAGCGCGATGACCGCCACAAACGCCCTGTTTTAGGCCGACCAAAACACATAT
GATAGCACCGCTGCATAGGGCCTGATATGCCAGTTACGCGGGACGCTGACGACGA
				</data>
				<hit pos="191" gap="153" motif="motif_1" pvalue="3.7e-01" strand="forward" match="+ + +    +  +++ +"/>
				<hit pos="214" gap="6" motif="motif_1" pvalue="2.8e-07" strand="reverse" match="++++++++ ++++++++"/>
				<hit pos="264" gap="33" motif="motif_1" pvalue="8.8e-01" strand="reverse" match="+ + ++ ++ + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_262" db="db_1" num="262" name="NP_280033.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.14e-06" evalue="0.00046"/>
			<seg start="1">
				<data>
AGTCGACGGAGGCCGAGCGCATCGCCGCGCTCGTCCATCGAGTCAGTGACATCTACGATGACGACGCCGACGTGG
				</data>
				<hit pos="48" gap="47" motif="motif_1" pvalue="9.9e-01" strand="reverse" match=" + + + +  ++++   "/>
			</seg>
			<seg start="76">
				<data>
ACGCCCAACACGTATATCTCAACATGCGAAACATCCTCCAGATCTCCGAGCAGGGCGGCATCGACCGATAACGCC
				</data>
				<hit pos="79" gap="14" motif="motif_1" pvalue="9.7e-01" strand="reverse" match="+  +++++ ++++    "/>
				<hit pos="114" gap="18" motif="motif_1" pvalue="7.6e-01" strand="reverse" match="++++ + +  +  +  +"/>
			</seg>
			<seg start="151">
				<data>
GCGGGGGTGTGGTCGCGTCCCTGCGGTCGCCCTCGGGCGGTCTTTCATCATTTTTCTGTGATAATGGATGGCAAA
CGATTTAGTGGCGACCACGCGTACGATGCCATATTGGTCCACGGCTGGGCCAGAC
				</data>
				<hit pos="192" gap="61" motif="motif_1" pvalue="5.7e-07" strand="forward" match="+++++++ +++ +++++"/>
				<hit pos="215" gap="6" motif="motif_1" pvalue="3.9e-01" strand="reverse" match="  ++   + ++ +++  "/>
				<hit pos="238" gap="6" motif="motif_1" pvalue="8.4e-01" strand="reverse" match=" +  ++ + ++ +++  "/>
			</seg>
		</sequence>
		<sequence id="seq_1_379" db="db_1" num="379" name="NP_280034.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.14e-06" evalue="0.00046"/>
			<seg start="1">
				<data>
AGTCGACGGAGGCCGAGCGCATCGCCGCGCTCGTCCATCGAGTCAGTGACATCTACGATGACGACGCCGACGTGG
				</data>
				<hit pos="48" gap="47" motif="motif_1" pvalue="9.9e-01" strand="reverse" match=" + + + +  ++++   "/>
			</seg>
			<seg start="76">
				<data>
ACGCCCAACACGTATATCTCAACATGCGAAACATCCTCCAGATCTCCGAGCAGGGCGGCATCGACCGATAACGCC
				</data>
				<hit pos="79" gap="14" motif="motif_1" pvalue="9.7e-01" strand="reverse" match="+  +++++ ++++    "/>
				<hit pos="114" gap="18" motif="motif_1" pvalue="7.6e-01" strand="reverse" match="++++ + +  +  +  +"/>
			</seg>
			<seg start="151">
				<data>
GCGGGGGTGTGGTCGCGTCCCTGCGGTCGCCCTCGGGCGGTCTTTCATCATTTTTCTGTGATAATGGATGGCAAA
CGATTTAGTGGCGACCACGCGTACGATGCCATATTGGTCCACGGCTGGGCCAGAC
				</data>
				<hit pos="192" gap="61" motif="motif_1" pvalue="5.7e-07" strand="forward" match="+++++++ +++ +++++"/>
				<hit pos="215" gap="6" motif="motif_1" pvalue="3.9e-01" strand="reverse" match="  ++   + ++ +++  "/>
				<hit pos="238" gap="6" motif="motif_1" pvalue="8.4e-01" strand="reverse" match=" +  ++ + ++ +++  "/>
			</seg>
		</sequence>
		<sequence id="seq_1_16" db="db_1" num="16" name="NP_280362.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_19" db="db_1" num="19" name="NP_280360.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_63" db="db_1" num="63" name="NP_280358.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_67" db="db_1" num="67" name="NP_280356.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_83" db="db_1" num="83" name="NP_280354.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_256" db="db_1" num="256" name="NP_280359.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_257" db="db_1" num="257" name="NP_280357.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_261" db="db_1" num="261" name="NP_280355.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_367" db="db_1" num="367" name="NP_280353.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_373" db="db_1" num="373" name="NP_444222.1" comment="" length="280">
			<score strand="both" combined_pvalue="1.66e-06" evalue="0.00067"/>
			<seg start="76">
				<data>
AGCACGCCCAAGTCCCCGTTCGCCCGTGATTCGACCATTACTGCAAGTTCAGACGACCCCAATTCAAGTAGTTTT
GTGTAACCGCCGGCGTCGGGGGCGCTCGCGCCCATCTAAGAAAGCTCACTTTCCCTAATACAATCAAAATTGTTT
TGGGTGCTTCTGACGTTGTGCCACCGATGGCACAGACACAGCTCCCGCACGACGC
				</data>
				<hit pos="92" gap="91" motif="motif_1" pvalue="3.1e-01" strand="forward" match="+ +++    +++ ++ +"/>
				<hit pos="111" gap="2" motif="motif_1" pvalue="6.6e-01" strand="forward" match="+ ++  +    ++++ +"/>
				<hit pos="135" gap="7" motif="motif_1" pvalue="1.1e-02" strand="forward" match="+ +++  + + ++++++"/>
				<hit pos="186" gap="34" motif="motif_1" pvalue="4.6e-01" strand="reverse" match="+ ++  ++    + +  "/>
				<hit pos="211" gap="8" motif="motif_1" pvalue="8.3e-07" strand="forward" match="+ ++++ ++++++++++"/>
				<hit pos="232" gap="4" motif="motif_1" pvalue="3.3e-01" strand="forward" match="+++ +    ++++ +  "/>
				<hit pos="264" gap="15" motif="motif_1" pvalue="9.2e-01" strand="reverse" match="+++  + +  + ++   "/>
			</seg>
		</sequence>
		<sequence id="seq_1_245" db="db_1" num="245" name="NP_281136.1" comment="" length="280">
			<score strand="both" combined_pvalue="2.25e-05" evalue="0.0091"/>
			<seg start="1">
				<data>
CGTGGGTCCGCGTCGACTGCAGTGACATCCGGTTCGGTCACGATCACAGCGTCTGCCTCCCGTGGTCGGCATTCC
				</data>
				<hit pos="34" gap="33" motif="motif_1" pvalue="9.8e-01" strand="reverse" match="  +  +++ +  + +  "/>
			</seg>
			<seg start="76">
				<data>
CCTCCCATGCCAGTCATTACCGCAAGCGTGTCAACGGTGGAATGTAAAGCTTGTCAAACGGTATGCATTAGCGTG
				</data>
				<hit pos="85" gap="34" motif="motif_1" pvalue="9.9e-01" strand="reverse" match="+ +  ++ ++  + +++"/>
				<hit pos="130" gap="28" motif="motif_1" pvalue="7.6e-01" strand="forward" match="+ + +  +++   ++ +"/>
			</seg>
			<seg start="151">
				<data>
ACGCTGGGCGTGCGATGTCGCGCGCGAACGAACATTCAAGCCGATCGGGTTGCAGAACAACAACGATGGCACGAC
				</data>
				<hit pos="174" gap="27" motif="motif_1" pvalue="5.3e-01" strand="reverse" match="  ++++ +  ++  +++"/>
				<hit pos="203" gap="12" motif="motif_1" pvalue="1.1e-05" strand="reverse" match="++++++++ ++ +++ +"/>
			</seg>
		</sequence>
		<sequence id="seq_1_124" db="db_1" num="124" name="NP_395816.1" comment="" length="280">
			<score strand="both" combined_pvalue="2.40e-05" evalue="0.0097"/>
			<seg start="1">
				<data>
AAGGGAGAGCTTCCGAACGGCGCGGACGCCACTGTACGAACACAGATTATTCTCCAGTGCCACGTTGACGGGTGT
TCTACGCAGACCCGGCTCAGCCGTGCACGAACACGTGGGTTCATCTGTCGAGCCCATTCCGACGTGGCCTAGAAC
				</data>
				<hit pos="32" gap="31" motif="motif_1" pvalue="4.4e-01" strand="reverse" match="+ + ++ +  + + +  "/>
				<hit pos="63" gap="14" motif="motif_1" pvalue="1.1e-01" strand="forward" match="+ ++ +   +++++++ "/>
				<hit pos="98" gap="18" motif="motif_1" pvalue="9.3e-01" strand="reverse" match="  + ++ +  + +   +"/>
				<hit pos="130" gap="15" motif="motif_1" pvalue="7.1e-01" strand="forward" match="+ +++  + +++  ++ "/>
			</seg>
			<seg start="151">
				<data>
GCCCCGGTTATTGTTAGTACGCTATTGTTTCCGCGGCTCGGATCATCTAGTGAGTGTATAACATCGCTCCTTTTA
TTATCGATCTAACTAGAACTCAGAGTATGTGGAACGTAGATGTAACTTGCATCGG
				</data>
				<hit pos="165" gap="18" motif="motif_1" pvalue="2.4e-01" strand="reverse" match=" ++ ++ +++ ++ +  "/>
				<hit pos="195" gap="13" motif="motif_1" pvalue="7.4e-01" strand="forward" match=" + +  + +++++ +  "/>
				<hit pos="220" gap="8" motif="motif_1" pvalue="1.2e-05" strand="forward" match="++++++++++ + +++ "/>
				<hit pos="239" gap="2" motif="motif_1" pvalue="6.5e-01" strand="reverse" match=" +++++ +  +  ++  "/>
				<hit pos="262" gap="6" motif="motif_1" pvalue="8.6e-01" strand="reverse" match=" +++   +   ++ +  "/>
			</seg>
		</sequence>
		<sequence id="seq_1_229" db="db_1" num="229" name="NP_280796.1" comment="" length="280">
			<score strand="both" combined_pvalue="2.55e-05" evalue="0.01"/>
			<seg start="1">
				<data>
AGCACGCGATCCTCGGCGTCGATGTCAAGCATCGACAGCGCCTCCGCGCGCATTTCCTCGGTCCAAATGAACGTG
TTGACGCGGTCGTACACCTTCGAGAGGTACTTGTAAAACGTGCGGGCCCGCGCCTTGTCTTCGAGGACTCCCATC
GACCGACTGTTGGCCTGAACACGCATAATAGCTTCCGATGGCCCAGGGACTTCGCAACTACCATATAGCACGTCC
				</data>
				<hit pos="64" gap="63" motif="motif_1" pvalue="3.2e-01" strand="forward" match="+ + +  + +++++   "/>
				<hit pos="92" gap="11" motif="motif_1" pvalue="9.4e-02" strand="forward" match="+ +++   ++    +++"/>
				<hit pos="146" gap="37" motif="motif_1" pvalue="3.8e-01" strand="forward" match="+ +++    +  + +++"/>
				<hit pos="165" gap="2" motif="motif_1" pvalue="1.3e-05" strand="reverse" match="+ ++++++  +++++++"/>
				<hit pos="200" gap="18" motif="motif_1" pvalue="9.8e-01" strand="reverse" match="+    +++ ++  +++ "/>
			</seg>
			<seg start="226">
				<data>
GCTAACCCCCACCTGGTTAGAGCGTATGCCAAGGCCAGAGGTTCTCGAAGACATC
				</data>
				<hit pos="243" gap="26" motif="motif_1" pvalue="8.7e-01" strand="reverse" match=" +++ +   +   ++ +"/>
			</seg>
		</sequence>
		<sequence id="seq_1_291" db="db_1" num="291" name="NP_280804.1" comment="" length="280">
			<score strand="both" combined_pvalue="2.55e-05" evalue="0.01"/>
			<seg start="76">
				<data>
GTCAGAGAGCCGCTGCTCGCGGTCCTCCTCGGCCTCGGCCACGATGTCGTCGGCGTCTGACTCTGCCGATTTGAT
GTCTTCGAGAACCTCTGGCCTTGGCATACGCTCTAACCAGGTGGGGGTTAGCGGACGTGCTATATGGTAGTTGCG
AAGTCCCTGGGCCATCGGAAGCTATTATGCGTGTTCAGGCCAACAGTCGGTCGAT
				</data>
				<hit pos="78" gap="77" motif="motif_1" pvalue="8.0e-01" strand="reverse" match="++++   +   ++ + +"/>
				<hit pos="119" gap="24" motif="motif_1" pvalue="9.2e-01" strand="forward" match=" + ++ +  + ++ +  "/>
				<hit pos="143" gap="7" motif="motif_1" pvalue="5.1e-01" strand="forward" match="  +++  + +  +   +"/>
				<hit pos="169" gap="9" motif="motif_1" pvalue="8.7e-01" strand="forward" match="+ ++   +   + +++ "/>
				<hit pos="212" gap="26" motif="motif_1" pvalue="9.8e-01" strand="forward" match=" +++  ++ +++    +"/>
				<hit pos="247" gap="18" motif="motif_1" pvalue="1.3e-05" strand="forward" match="+++++++  ++++++ +"/>
			</seg>
		</sequence>
		<sequence id="seq_1_396" db="db_1" num="396" name="NP_280799.1" comment="" length="280">
			<score strand="both" combined_pvalue="2.55e-05" evalue="0.01"/>
			<seg start="1">
				<data>
AGCACGCGATCCTCGGCGTCGATGTCAAGCATCGACAGCGCCTCCGCGCGCATTTCCTCGGTCCAAATGAACGTG
TTGACGCGGTCGTACACCTTCGAGAGGTACTTGTAAAACGTGCGGGCCCGCGCCTTGTCTTCGAGGACTCCCATC
GACCGACTGTTGGCCTGAACACGCATAATAGCTTCCGATGGCCCAGGGACTTCGCAACTACCATATAGCACGTCC
				</data>
				<hit pos="64" gap="63" motif="motif_1" pvalue="3.2e-01" strand="forward" match="+ + +  + +++++   "/>
				<hit pos="92" gap="11" motif="motif_1" pvalue="9.4e-02" strand="forward" match="+ +++   ++    +++"/>
				<hit pos="146" gap="37" motif="motif_1" pvalue="3.8e-01" strand="forward" match="+ +++    +  + +++"/>
				<hit pos="165" gap="2" motif="motif_1" pvalue="1.3e-05" strand="reverse" match="+ ++++++  +++++++"/>
				<hit pos="200" gap="18" motif="motif_1" pvalue="9.8e-01" strand="reverse" match="+    +++ ++  +++ "/>
			</seg>
			<seg start="226">
				<data>
GCTAACCCCCACCTGGTTAGAGCGTATGCCAAGGCCAGAGGTTCTCGAAGACATC
				</data>
				<hit pos="243" gap="26" motif="motif_1" pvalue="8.7e-01" strand="reverse" match=" +++ +   +   ++ +"/>
			</seg>
		</sequence>
		<sequence id="seq_1_397" db="db_1" num="397" name="NP_280803.1" comment="" length="280">
			<score strand="both" combined_pvalue="2.55e-05" evalue="0.01"/>
			<seg start="1">
				<data>
AGCACGCGATCCTCGGCGTCGATGTCAAGCATCGACAGCGCCTCCGCGCGCATTTCCTCGGTCCAAATGAACGTG
TTGACGCGGTCGTACACCTTCGAGAGGTACTTGTAAAACGTGCGGGCCCGCGCCTTGTCTTCGAGGACTCCCATC
GACCGACTGTTGGCCTGAACACGCATAATAGCTTCCGATGGCCCAGGGACTTCGCAACTACCATATAGCACGTCC
				</data>
				<hit pos="64" gap="63" motif="motif_1" pvalue="3.2e-01" strand="forward" match="+ + +  + +++++   "/>
				<hit pos="92" gap="11" motif="motif_1" pvalue="9.4e-02" strand="forward" match="+ +++   ++    +++"/>
				<hit pos="146" gap="37" motif="motif_1" pvalue="3.8e-01" strand="forward" match="+ +++    +  + +++"/>
				<hit pos="165" gap="2" motif="motif_1" pvalue="1.3e-05" strand="reverse" match="+ ++++++  +++++++"/>
				<hit pos="200" gap="18" motif="motif_1" pvalue="9.8e-01" strand="reverse" match="+    +++ ++  +++ "/>
			</seg>
			<seg start="226">
				<data>
GCTAACCCCCACCTGGTTAGAGCGTATGCCAAGGCCAGAGGTTCTCGAAGACATC
				</data>
				<hit pos="243" gap="26" motif="motif_1" pvalue="8.7e-01" strand="reverse" match=" +++ +   +   ++ +"/>
			</seg>
		</sequence>
		<sequence id="seq_1_399" db="db_1" num="399" name="NP_280797.2" comment="" length="280">
			<score strand="both" combined_pvalue="2.55e-05" evalue="0.01"/>
			<seg start="1">
				<data>
AGCACGCGATCCTCGGCGTCGATGTCAAGCATCGACAGCGCCTCCGCGCGCATTTCCTCGGTCCAAATGAACGTG
TTGACGCGGTCGTACACCTTCGAGAGGTACTTGTAAAACGTGCGGGCCCGCGCCTTGTCTTCGAGGACTCCCATC
GACCGACTGTTGGCCTGAACACGCATAATAGCTTCCGATGGCCCAGGGACTTCGCAACTACCATATAGCACGTCC
				</data>
				<hit pos="64" gap="63" motif="motif_1" pvalue="3.2e-01" strand="forward" match="+ + +  + +++++   "/>
				<hit pos="92" gap="11" motif="motif_1" pvalue="9.4e-02" strand="forward" match="+ +++   ++    +++"/>
				<hit pos="146" gap="37" motif="motif_1" pvalue="3.8e-01" strand="forward" match="+ +++    +  + +++"/>
				<hit pos="165" gap="2" motif="motif_1" pvalue="1.3e-05" strand="reverse" match="+ ++++++  +++++++"/>
				<hit pos="200" gap="18" motif="motif_1" pvalue="9.8e-01" strand="reverse" match="+    +++ ++  +++ "/>
			</seg>
			<seg start="226">
				<data>
GCTAACCCCCACCTGGTTAGAGCGTATGCCAAGGCCAGAGGTTCTCGAAGACATC
				</data>
				<hit pos="243" gap="26" motif="motif_1" pvalue="8.7e-01" strand="reverse" match=" +++ +   +   ++ +"/>
			</seg>
		</sequence>
		<sequence id="seq_1_388" db="db_1" num="388" name="NP_395893.1" comment="" length="280">